In [1]:
# readlines 파일의 모든 줄을 읽어서 각각의 줄을 요소로 갖는 리스트로 돌려준다.
f = open("c:/workspace/r/2.Python/테스트폴더/새파일.txt", "r") # 읽기모드 
list1 = []
lines = f.readlines()
f.close() # 열고 닫고 잘 처리해야
print(lines)
for item in lines:                     # 줄 바꿈 없애주기
    processed = item.replace("\n","")
    list1.append(processed)            # 리스트 처리
print(list1)

['zzzzzzzzzzzzzzz\n', 'xxxxxxxxxxxx\n', 'ssssssssssss\n', 'ddddddddddddㅋㅋㅋㅋㅋㅋㅎㅎㅎㅎㅎㅎ']
['zzzzzzzzzzzzzzz', 'xxxxxxxxxxxx', 'ssssssssssss', 'ddddddddddddㅋㅋㅋㅋㅋㅋㅎㅎㅎㅎㅎㅎ']


In [2]:
# 선생님 답안
f = open("c:/workspace/r/2.Python/테스트폴더/새파일.txt", "r") # 읽기모드 
lines = f.readlines()
f.close() # 열고 닫고 잘 처리해야
print(lines)
list1 = []
for item in lines:                     # 줄 바꿈 없애주기
    list1.append(item.replace("\n",""))# 리스트 처리
print(list1)

['zzzzzzzzzzzzzzz\n', 'xxxxxxxxxxxx\n', 'ssssssssssss\n', 'ddddddddddddㅋㅋㅋㅋㅋㅋㅎㅎㅎㅎㅎㅎ']
['zzzzzzzzzzzzzzz', 'xxxxxxxxxxxx', 'ssssssssssss', 'ddddddddddddㅋㅋㅋㅋㅋㅋㅎㅎㅎㅎㅎㅎ']


In [3]:
#read 함수 사용
f = open("c:/workspace/r/2.Python/테스트폴더/새파일.txt", "r") # 읽기모드 
page = f.read()
f.close() # 열고 닫고 잘 처리해야
print(page)
refined_list = page.split("\n") # split을 활용해 나눠주고 리스트 처리함.
print(refined_list)

zzzzzzzzzzzzzzz
xxxxxxxxxxxx
ssssssssssss
ddddddddddddㅋㅋㅋㅋㅋㅋㅎㅎㅎㅎㅎㅎ
['zzzzzzzzzzzzzzz', 'xxxxxxxxxxxx', 'ssssssssssss', 'ddddddddddddㅋㅋㅋㅋㅋㅋㅎㅎㅎㅎㅎㅎ']


In [4]:
# 노코드가 뜰날도 멀지 않았다.

In [5]:
f = open("c:/workspace/r/2.Python/테스트폴더/새파일.txt", "a") # 추가 모드는 기존에 있던 파일에 내용을 추가하는 것 
f.write("ㅋㅋㅋ")                                              # 쓰기 모드는 기존에 있던 내용을 지우고 내용을 새로 추가한다.
f.close()

In [6]:
# with문
with open("c:/workspace/r/2.Python/테스트폴더/새파일.txt", "a") as f: # 간단해지는 대신 "as" 와 "들여쓰기"를 해야함.
    f.write("ㅎㅎㅎ")                                            

In [7]:
##### 클래스 "객체 지향적 프로그래밍(Class, Object)"
# 이전에 우리가 배운 기본적 코드 양식은 모두 " 절차 지향적 프로그래밍이다. (procedure)"

In [8]:
class FourCal : # 설계도를 만듭니다 (self = 우리 식구에요)
    # self.first  #####정적인 부분
    # self. second
    def setdata(self,a,b):
        self.first = a
        self.second = b
    def add(self): # 함수안에 self라는 말이 들어가줘서 클래스 안 구성요소 가능 #### 동적인 부분
        result = self.first + self.second
        return result # result 는 내부 구성 요소로서 중요하지 않더라 / 속성은 아니고 소모품?
    def mul(self): 
        result = self.first * self.second
        return result
    
# 사람
## 얼굴(정적), 직립보행(동작), 이름(정적), 언어(동적)

# 자동차
## 바퀴, 창문, 엔진 / 전진, 후진, 좌회전, 창문올림.

aCal = FourCal()
bCal = FourCal()  # 객체
aCal.setdata(4,2) # 세팅
print(aCal.add())
bCal.setdata(3,8)
print(bCal.add())

6
11


In [9]:
class FourCal : 
    def __init__(self,a,b): # 객체와 세팅을 처음에 모두 진행함.
        self.first = a
        self.second = b
    def add(self): 
        result = self.first + self.second
        return result
    def mul(self): 
        result = self.first * self.second
        return result
    
aCal = FourCal(4,2)         # 세팅 필요없이 인수를 직접 넣어 출력
bCal = FourCal(3,8)

print(aCal.add())
print(bCal.add())

6
11


In [10]:
# 상속
class FourCal : 
    def __init__(self,a,b): # 객체와 세팅을 처음에 모두 진행함.
        self.first = a
        self.second = b
    def add(self): 
        result = self.first + self.second
        return result
    def mul(self): 
        result = self.first * self.second
        return result

class MoreFourcal(FourCal): #부모 계승
    pass

c = MoreFourcal(4,2)        #부모의 기능 잘 계승함을 볼 수 있음.
d = c.add()
print(d)

6


In [11]:
# 상속 심화
class FourCal : 
    def __init__(self,a,b): # 객체와 세팅을 처음에 모두 진행함.
        self.first = a
        self.second = b
    def add(self): 
        result = self.first + self.second
        return result
    def mul(self): 
        result = self.first * self.second
        return result

class MoreFourcal(FourCal): #부모 계승
    def pow(self):
        result = self.first**self.second
        return result

c = MoreFourcal(4,2)       # 새로운 자기만에 기능 또한 추가할 수 있음.
d = c.pow()
print(d)

16


In [12]:
# 상속 심화 2 (부모 보완, 0으로 나눌때 값이 안나옴)
class FourCal : 
    def __init__(self,a,b): # 객체와 세팅을 처음에 모두 진행함.
        self.first = a
        self.second = b
    def add(self): 
        result = self.first + self.second
        return result
    def mul(self): 
        result = self.first * self.second
        return result
    def div(self):
        result = self.first / self.second  # 0일때 못 나누는 함정이 발생함.
        return result

class MoreFourcal(FourCal): #부모 계승
    def pow(self):
        result = self.first**self.second
        return result
    def div(self):
        if self.second == 0:
            self.second = 0.0000000000001
        result = self.first / self.second   # 0일때 못 나누는 함정을 자식에서 수정함 
        return result

c = MoreFourcal(4,0)       
d = c.div()
print(d)

40000000000000.0


In [13]:
# 클래스 변수 (클래스 속에 고정된 변수를 넣을 수 도 있다.)
class MyMath:
    MyPI = 3.14

mm = MyMath()
print(mm.MyPI)

3.14


In [14]:
# 클래스 변수 (클래스 속에 고정된 변수를 넣을 수 도 있다.)
class MyMath:
    MyPI = 3.14

mm1 = MyMath()
mm1.MyPI = 4
mm2 = MyMath()
print(mm1.MyPI, mm2.MyPI)

4 3.14


In [15]:
##### 모듈(외부 라이브러리를 불러옴)
import mod1 # 에러가 안났으니 잘된 증거
print(mod1.add_mod1(3,4))
print(mod1.sub_mod1(3,4))

7
-1


In [16]:
import mod1 as m1       # 다른말로 바꿔줄 수 있음.
print(m1.add_mod1(3,4))
print(m1.sub_mod1(3,4))

7
-1


In [17]:
from mod1 import add_mod1, sub_mod1 # 활용도가 제일 높음.
print(add_mod1(3,4))
print(sub_mod1(3,4))

7
-1


In [18]:
from mod1 import * # 모듈마다 이름이 겹치고 많아지면 충돌할 수 있기 때문에 모두 다 끌어오는 기능보단 위처럼 필요한 것만 가져온다.
print(add_mod1(3,4))
print(sub_mod1(3,4))

7
-1


In [19]:
import mod2 # 에러가 안났으니 잘된 증거
print(mod2.add_mod2(3,4))
print(mod2.PI)
mm2 = mod2.Math_Mod2() # 클래스 불러오기
print(mm2.solve(2))

7
3.14
12.56


In [20]:
# P 216 패키지 (패키지 불러오기, 세 가지 가지고 노는데 우리 한달차에 목표)

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [21]:
# P 222 예외처리
try:
    print(4/0)
except ZeroDivisionError as e:
    print(4/0.000000000000001)
    # print(e)

3999999999999999.5


In [22]:
# 내장 함수는 import를 사용할 필요없다.

In [23]:
# P 235 파이썬 기본문법 활용
def positive(l) :
    result=[]
    for i in l:
        if i > 0: result.append(i)
    return result

print(positive([1, -3, 2, 0, -5, 6])) # 양수만 살아 남기는 필터

[1, 2, 6]


In [24]:
# P 235 필터 활용 직관적인 것 이용 多
def positive(x):
    return x >0
data = [1, -3, 2, 0, -5, 6]
f = filter(positive, data)
print(list(f))

[1, 2, 6]


In [25]:
# lambda 활용 효율성 추구
data = [1, -3, 2, 0, -5, 6]
list(filter(lambda x: x>0, data))

[1, 2, 6]

In [26]:
# map 함수와 input 같이 사용하기

a = int(input("숫자를 입력하세요")) # 숫자가 문자열로 나오니 int 처리
a = a + 1
print(a)

숫자를 입력하세요10
11


In [28]:
# 숫자 여러개 넣기

a, b = input("숫자 두개를 입력하세요").split()
a = int(a)
b = int(b)
print(a+1, "그리고", b+1)

숫자 두개를 입력하세요10 20
11 그리고 21


In [30]:
# 숫자 여러개 넣기 심화 

a, b = map(int, input("숫자 두개를 입력하세요").split())
print(a+1, "그리고", b+1)

숫자 두개를 입력하세요10 20
11 그리고 21


In [34]:
# P 246 zip

data1 = [1, 2, 3]
data2 = [4, 5, 6]
list(zip(data1, data2)) # 같은 위치(n번째)의 원소(=아이템)끼리 묶음.

[(1, 4), (2, 5), (3, 6)]

In [35]:
data1 = [1, 2, 3]
data2 = [4, 5, 6]
data3 = [7, 8, 9]
list(zip(data1, data2, data3))

[(1, 4, 7), (2, 5, 8), (3, 6, 9)]

In [38]:
# P 250 OS

import os
os.environ["path"]

'C:\\ProgramData\\Anaconda3;C:\\ProgramData\\Anaconda3\\Library\\mingw-w64\\bin;C:\\ProgramData\\Anaconda3\\Library\\usr\\bin;C:\\ProgramData\\Anaconda3\\Library\\bin;C:\\ProgramData\\Anaconda3\\Scripts;C:\\Program Files\\Common Files\\Oracle\\Java\\javapath;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\iCLS\\;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\iCLS\\;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Windows\\System32\\OpenSSH\\;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files\\Intel\\WiFi\\bin\\;C:\\Program Files\\Common Files\\Intel\\WirelessCommon\\;C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common;C:\\Program Files\\NVIDIA Corporation\\NVIDIA NvDLISR;C:\\Program Files\\Git\\cmd;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\W

In [40]:
os.getcwd() # 현재 작업 위치를 알 수 있음.

'C:\\workspace\\R\\2.Python'

In [42]:
# P 252 glob

import glob
glob.glob('C:\\workspace\\R\\2.Python\\*.py') # 해당 경로에 .py형식의 파일을 모두 보여줌 

['C:\\workspace\\R\\2.Python\\mod1.py', 'C:\\workspace\\R\\2.Python\\mod2.py']

In [44]:
# P253 time

import time
time.time() # 1970년 1월 1일 0시 0분 0초를 기준으로 지난 시간을 초단위로 돌려줌

1622012879.7481902

In [47]:
time.localtime(time.time())

time.struct_time(tm_year=2021, tm_mon=5, tm_mday=26, tm_hour=16, tm_min=9, tm_sec=9, tm_wday=2, tm_yday=146, tm_isdst=0)

In [50]:
time.asctime(time.localtime(time.time())).split()

['Wed', 'May', '26', '16:10:10', '2021']

In [52]:
for i in range(10):
    print(i)
    time.sleep(1) # 차근차근 하나씩 보여줌 

0
1
2
3
4
5
6
7
8
9


In [54]:
import random
random.random() # 0 ~ 1 사이값 출력

0.1744075232802581

In [56]:
random.randint(1,10) # 범위를 줄 수 있음 1 ~10

3

In [57]:
########### Python For data analysis P 135

In [73]:
# 다차원 배열 객체 NumPy ndarray
import numpy as np
my_arr = np.arange(1000000) # 넘파이식으로
my_list = list(range(1000000)) # 기존의 파이썬식으로
%time for i in range(10): my_arr2 = my_arr*2
# 속도차이가 50배 가까이 남

Wall time: 15 ms


In [75]:
%time for i in range(10): my_list2=[x * 2 for x in my_list]
# 속도차이가 50배 가까이 남

Wall time: 742 ms


In [68]:
data = np.random.randn(2,3) # 2행 3열의 행렬 생성
data

array([[-0.42829125, -0.47401914,  0.61703571],
       [-0.25401706,  0.35645096,  0.62755735]])

In [70]:
data * 10 # 행렬 원소 안에 각각 10배

array([[-4.28291255, -4.74019136,  6.17035712],
       [-2.54017062,  3.56450964,  6.27557354]])

In [76]:
data + data # 행렬의 같은 주소끼리 더함

array([[-0.85658251, -0.94803827,  1.23407142],
       [-0.50803412,  0.71290193,  1.25511471]])

In [78]:
data.shape # 행렬 계산에 앞서 형태를 보기위해서 필요시엔 전치를 해야함.

(2, 3)

In [80]:
data.dtype # float은 실수형

dtype('float64')

In [83]:
#1.1 P137 ndarray 생성하기 1차원
data = [6, 7.5, 8, 0, 1]
arr = np.array(data)
arr                    # 정수인 친구들에게 .을 붙여놓음.

array([6. , 7.5, 8. , 0. , 1. ])

In [88]:
# darray 생성하기 2차원 
data2d = [[1, 2, 3, 4],[5, 6, 7, 8]] # Python 식 표현 1,2행이 나란히 출력됨 
print(data2d)

arr2d = np.array(data2d)              # NumPy 식 표현 1,2행이 나눠서 출력됨 --> 훨씬 보기 좋음.
arr2d

[[1, 2, 3, 4], [5, 6, 7, 8]]


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [90]:
arr2d.ndim

2

In [92]:
arr2d.shape # 2행 4열이구나

(2, 4)

In [94]:
np.zeros(10) # 행렬을 만드는데 특별한 컨텐츠는 없이 출력함. 제로즈는 인수 하나만 가짐

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [96]:
np.zeros((3, 6)) # 2개 인수를 넣을때 튜플로 한번 묶어 제로즈 자체가 읽을때 하나로 인식하게끔 함.

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [99]:
np.zeros((2, 3, 4)) # 3차원 (층, 행, 열) / 3차원은 자주 사용 X

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [101]:
np.zeros((2, 3, 4)).dtype

dtype('float64')

In [104]:
# 데이터 타입 바꾸기 
arr = np.zeros((2, 3, 4), dtype=np.int32) # 정수 32비트로 바꿀꺼야
arr.dtype

dtype('int32')

In [108]:
# ones_like
arr1 = np.zeros((2, 3))   # 2행 3열
arr2 = np.ones_like(arr1) # like를 써서 arr1과 비슷한거 만들어주세요~
print(arr2.shape)
arr2

(2, 3)


array([[1., 1., 1.],
       [1., 1., 1.]])

In [110]:
# full
arr3 = np.full((2, 3), 5) # 2행3열을 5로 채우고 싶다.
arr3

array([[5, 5, 5],
       [5, 5, 5]])

In [113]:
arr4 = np.eye(2) # 단위행렬 n*n
arr4

array([[1., 0.],
       [0., 1.]])