In [1]:
# pytorch (기존엔 사이킷런을 이용한 것임.)
# 그래픽 카드에 대한 소식도 민감해야함 데이터 분석에 있어서

# CPU(central processing unit 중앙 처리 장치) : 명령어의 해석과 자료의 연산, 비교 등의 처리를 제어하는 컴퓨터 시스템의 핵심적인 장치(정수형 사칙연산)
# 코어개수 12개, 2.2GHz

# RAM(random access memory 중앙 기억 장치) : 기억된 정보를 읽어내기도 하고 다른 정보를 기억시킬 수도 있는 메모리

# 그래픽 카드 (AMD, nVidia) : 픽셀 처리(실수형 사칙연산) 
# GTX1060 1200개 1.5GHz

In [2]:
# !pip install torch cuba

In [3]:
import torch
import numpy as np

In [4]:
torch.__version__

'1.9.0+cpu'

In [5]:
data = [[1, 2], [3, 4]]

In [6]:
np_data = np.array(data)

In [7]:
np_data

array([[1, 2],
       [3, 4]])

In [8]:
x_data = torch.tensor(data)

In [9]:
x_data # nunpy랑 굉장히 비슷한 모양으로 보임.

tensor([[1, 2],
        [3, 4]])

In [10]:
x_data_f = torch.FloatTensor(data)
x_data_f

tensor([[1., 2.],
        [3., 4.]])

In [11]:
print(x_data_f.dim)

<built-in method dim of Tensor object at 0x000002114F02A280>


In [12]:
print(x_data_f.shape)

torch.Size([2, 2])


In [13]:
x_data_f[0][1]

tensor(2.)

In [14]:
t1 = torch.FloatTensor([[1,3]])
t2 = torch.FloatTensor([[2,4]])
print(t1 + t2)

tensor([[3., 7.]])


In [15]:
t1 = torch.FloatTensor([[1,3]])
t2 = torch.FloatTensor([[2]])
print(t1+t2)

tensor([[3., 5.]])


In [16]:
x_data_f.mean() # 1,2,3,4

tensor(2.5000)

In [17]:
x_data_f.mean(dim=0)
# 1 2
# 3 4

tensor([2., 3.])

In [18]:
x_data_f.mean(dim=1)
# 1 2
# 3 4

tensor([1.5000, 3.5000])

In [19]:
t1 = torch.FloatTensor([[1,3]])
t2 = torch.FloatTensor([[2,4]])

In [20]:
torch.cat([t1, t2], dim = 0)

tensor([[1., 3.],
        [2., 4.]])

In [21]:
torch.cat([t1, t2], dim = 1)

tensor([[1., 3., 2., 4.]])

In [22]:
t3 = torch.FloatTensor([[5,6]])
t4 = torch.stack([t1, t2, t3])
t4

tensor([[[1., 3.]],

        [[2., 4.]],

        [[5., 6.]]])

In [23]:
torch.ones_like(t4)

tensor([[[1., 1.]],

        [[1., 1.]],

        [[1., 1.]]])

In [24]:
torch.zeros_like(t4)

tensor([[[0., 0.]],

        [[0., 0.]],

        [[0., 0.]]])

In [25]:
# 1  ->2
# 2  ->4
# 3  ->6
# y = 2x

In [26]:
X_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

In [27]:
# 가설 설정
# y = W * x + b
# 기존 사이킷런 머신 러닝: MSE 평균 제곱 오차

# cost funtion(비용함수) = loss function(손실함수) = error function(오차함수) = objective function(목적함수)
# 옵티마이져 (기울기가 제일 낮은 곳 , 경사 하강법(gradient descent) 사용) (Ex. 머신러닝에서 fit)

In [28]:
print(X_train.shape)

torch.Size([3, 1])


In [29]:
print(y_train.shape)

torch.Size([3, 1])


In [30]:
W = torch.zeros(1, requires_grad = True) # 바꿔가면서 쓸 변수다 .
# 기울기를 0으로 세팅

In [31]:
print(W)

tensor([0.], requires_grad=True)


In [32]:
b = torch.zeros(1, requires_grad = True) # 바꿔가면서 쓸 변수다 .
# 바이어스 0으로 세팅

In [33]:
print(b)

tensor([0.], requires_grad=True)


In [34]:
# 현재 세팅 값 y = 0*x + 0

In [35]:
# 가설
hypothesis = X_train*W+b

In [36]:
print(hypothesis) 

tensor([[0.],
        [0.],
        [0.]], grad_fn=<AddBackward0>)


In [37]:
cost = torch.mean((hypothesis - y_train)**2) # 원본값과 비교 / 평균 제곱 오차

In [38]:
print(cost)

tensor(18.6667, grad_fn=<MeanBackward0>)


In [39]:
# SGD 경사 하강법 적용 / lr 러닝 레이트가 너무 크면 빨리 찾아갈 수는 있지만 어디에 수렴하질 못함(발산한다) / 작게 잡으면 늦어질순 있지만 발산 정도는 낮아진다.
import torch.optim as optim
optimizer = optim.SGD([W, b], lr = 0.01)

In [40]:
# 0으로 시작하겠다
optimizer.zero_grad()

In [41]:
# 추적
cost.backward()

In [42]:
# 추적값 업데이트
optimizer.step()

In [44]:
# 종합

t1 = torch.FloatTensor([[1,3]])
t2 = torch.FloatTensor([[2,4]])

X_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

W = torch.zeros(1, requires_grad = True)
b = torch.zeros(1, requires_grad = True)

optimizer = optim.SGD([W, b], lr = 0.001)

# iter_ 값과 같은 반복요구값
nb_epochs = 20000
list_cost = []
for epoch in range(nb_epochs):
    hypothesis = X_train*W+b
    cost = torch.mean((hypothesis - y_train)**2)
    
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    # 중간마다 확인하고 싶다
    if epoch % 200 == 0:
        # list_cost.append(float(cost.item()))
        print('Epoch{:4d}/{} W: {:.3f}, b:{:.3f} , cost{:.5f}'.
             format( epoch, nb_epochs, W.item(), b.item(), cost.item()))
        
# import matplotlib.pyplot as plt
# print()
# plt.plot(range(100), list_cost)

Epoch   0/20000 W: 0.019, b:0.008 , cost18.66667
Epoch 200/20000 W: 1.513, b:0.624 , cost0.28531
Epoch 400/20000 W: 1.686, b:0.661 , cost0.06679
Epoch 600/20000 W: 1.717, b:0.637 , cost0.05845
Epoch 800/20000 W: 1.732, b:0.608 , cost0.05306
Epoch1000/20000 W: 1.745, b:0.579 , cost0.04820
Epoch1200/20000 W: 1.757, b:0.552 , cost0.04378
Epoch1400/20000 W: 1.768, b:0.526 , cost0.03976
Epoch1600/20000 W: 1.779, b:0.502 , cost0.03612
Epoch1800/20000 W: 1.790, b:0.478 , cost0.03281
Epoch2000/20000 W: 1.800, b:0.456 , cost0.02980
Epoch2200/20000 W: 1.809, b:0.434 , cost0.02707
Epoch2400/20000 W: 1.818, b:0.414 , cost0.02458
Epoch2600/20000 W: 1.826, b:0.394 , cost0.02233
Epoch2800/20000 W: 1.835, b:0.376 , cost0.02028
Epoch3000/20000 W: 1.842, b:0.358 , cost0.01842
Epoch3200/20000 W: 1.850, b:0.341 , cost0.01673
Epoch3400/20000 W: 1.857, b:0.325 , cost0.01520
Epoch3600/20000 W: 1.864, b:0.310 , cost0.01381
Epoch3800/20000 W: 1.870, b:0.296 , cost0.01254
Epoch4000/20000 W: 1.876, b:0.282 , cos

In [45]:
# 가설 설정
# y = W1 * x1 + W2 * x2 + W3 * x3 + b

In [59]:
# feature 가 3 개 , 포인트가 5개 / 결과값이 1개
X1_train = torch.FloatTensor([[73], [93], [89], [96], [73]])
X2_train = torch.FloatTensor([[80], [88], [91], [98], [66]])
X3_train = torch.FloatTensor([[75], [93], [90], [100], [73]])

y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

W1 = torch.zeros(1, requires_grad = True)
W2 = torch.zeros(1, requires_grad = True)
W3 = torch.zeros(1, requires_grad = True)
b = torch.zeros(1, requires_grad = True)

optimizer = optim.SGD([W1,W2,W3, b], lr = 0.000008)
nb_epochs = 200000
list_cost = []
for epoch in range(nb_epochs):
    hypothesis = X1_train*W1+X2_train*W2+X3_train*W3+b
    cost = torch.mean((hypothesis - y_train)**2)
    
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    # 중간마다 확인하고 싶다
    if epoch % 5000 == 0:
        # list_cost.append(float(cost.item()))
        print('Epoch : {:4d}/{} W1 : {:.3f}, W2 : {:.3f}, W3 : {:.3f}, b : {:.3f} , cost : {:.5f}'.
             format( epoch, nb_epochs, W1.item(),W2.item(),W3.item(), b.item(), cost.item()))

# 다변량에 있어서 0으로 수렴하기는 어렵다
# W1, W2, W3, b 값이 바뀌지 않고 일정할 때 만족하는 것이 좋다.

Epoch :    0/200000 W1 : 0.235, W2 : 0.235, W3 : 0.239, b : 0.003 , cost : 29661.80078
Epoch : 5000/200000 W1 : 0.733, W2 : 0.582, W3 : 0.691, b : 0.007 , cost : 0.47267
Epoch : 10000/200000 W1 : 0.762, W2 : 0.558, W3 : 0.686, b : 0.006 , cost : 0.43392
Epoch : 15000/200000 W1 : 0.779, W2 : 0.553, W3 : 0.674, b : 0.005 , cost : 0.42241
Epoch : 20000/200000 W1 : 0.792, W2 : 0.553, W3 : 0.662, b : 0.004 , cost : 0.41417
Epoch : 25000/200000 W1 : 0.804, W2 : 0.555, W3 : 0.649, b : 0.003 , cost : 0.40692
Epoch : 30000/200000 W1 : 0.814, W2 : 0.557, W3 : 0.637, b : 0.002 , cost : 0.40039
Epoch : 35000/200000 W1 : 0.824, W2 : 0.559, W3 : 0.625, b : 0.001 , cost : 0.39449
Epoch : 40000/200000 W1 : 0.833, W2 : 0.561, W3 : 0.614, b : -0.001 , cost : 0.38914
Epoch : 45000/200000 W1 : 0.842, W2 : 0.563, W3 : 0.604, b : -0.002 , cost : 0.38429
Epoch : 50000/200000 W1 : 0.850, W2 : 0.564, W3 : 0.594, b : -0.004 , cost : 0.37991
Epoch : 55000/200000 W1 : 0.858, W2 : 0.566, W3 : 0.584, b : -0.005 , c

In [61]:
# 간소화
import torch.nn as nn

In [62]:
model = nn.Linear(1,1) # (input_dim=1, output_dim=1)

In [64]:
print(list(model.parameters())) # 첫번째 텐서 = W , 두번째 텐서 = b

[Parameter containing:
tensor([[0.2142]], requires_grad=True), Parameter containing:
tensor([-0.2737], requires_grad=True)]


In [ ]:
optimizer = optim.SGD(model.parameters(), lr = 0.000001)


In [71]:
import torch.nn as nn
import torch.nn.functional as F

X_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])
model = nn.Linear(1,1) # (input_dim=1, output_dim=1)

print(list(model.parameters())) # 첫번째 텐서 = W , 두번째 텐서 = b

optimizer = optim.SGD(model.parameters(), lr = 0.01)

nb_epochs = 2000
for epoch in range(nb_epochs+1):
    prediction = model(X_train)
    cost = F.mse_loss(prediction, y_train)   
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    if epoch % 100 == 0:
        print('Epoch : {:4d}/{} loss : {:.5f}'.format(epoch, nb_epochs, cost.item()))

[Parameter containing:
tensor([[0.9013]], requires_grad=True), Parameter containing:
tensor([-0.3672], requires_grad=True)]
Epoch :    0/2000 loss : 7.38154
Epoch :  100/2000 loss : 0.00084
Epoch :  200/2000 loss : 0.00052
Epoch :  300/2000 loss : 0.00032
Epoch :  400/2000 loss : 0.00020
Epoch :  500/2000 loss : 0.00012
Epoch :  600/2000 loss : 0.00008
Epoch :  700/2000 loss : 0.00005
Epoch :  800/2000 loss : 0.00003
Epoch :  900/2000 loss : 0.00002
Epoch : 1000/2000 loss : 0.00001
Epoch : 1100/2000 loss : 0.00001
Epoch : 1200/2000 loss : 0.00000
Epoch : 1300/2000 loss : 0.00000
Epoch : 1400/2000 loss : 0.00000
Epoch : 1500/2000 loss : 0.00000
Epoch : 1600/2000 loss : 0.00000
Epoch : 1700/2000 loss : 0.00000
Epoch : 1800/2000 loss : 0.00000
Epoch : 1900/2000 loss : 0.00000
Epoch : 2000/2000 loss : 0.00000


In [72]:
new_input = torch.FloatTensor([[1.5]])
pred_y =model(new_input)
pred_y

tensor([[3.0003]], grad_fn=<AddmmBackward>)