# Pandas
- 표 형식의 데이터나 다양한 형태의 데이터를 다루는데 초점을 맞춰 설계
- Numpy는 단일 산술 배열 데이터를 다루는데 특화

In [73]:
import pandas as pd
import numpy as np

In [4]:
from pandas import Series, DataFrame

- 자료 구조 소개
- Series, Dataframe

## Series
- 일련의 객체를 담을 수 있는 1차원 배열(어떤 Numpy 자료형이라도 담을 수 있음)
- 고정 길이의 정렬된 사전형

In [7]:
obj = pd.Series([4, 7, -5, 3])

In [8]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [9]:
obj.values

array([ 4,  7, -5,  3], dtype=int64)

In [10]:
obj.index

RangeIndex(start=0, stop=4, step=1)

- 색인 지정

In [23]:
obj2 = pd.Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])

In [24]:
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [25]:
obj2['a']

-5

In [26]:
obj2['d'] = 6

In [27]:
obj2

d    6
b    7
a   -5
c    3
dtype: int64

In [28]:
obj2[obj2 > 0]

d    6
b    7
c    3
dtype: int64

In [29]:
obj2 * 2

d    12
b    14
a   -10
c     6
dtype: int64

### 사전형 대체 사용

In [30]:
'b' in obj2

True

In [31]:
'e' in obj2

False

In [36]:
sdata = {'Ohio' : 35000, 'Texas' : 71000, 'Oregon' : 16000, 'Utah' : 5000}

In [37]:
sdata

{'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

In [34]:
odj3 = pd.Series(sdata)

In [35]:
odj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

### 색인 지정

In [39]:
states = ['Califonia', 'Ohio', 'Oregon', 'Texas']

In [40]:
obj4 = pd.Series(sdata, index=states)

In [41]:
obj4

Califonia        NaN
Ohio         35000.0
Oregon       16000.0
Texas        71000.0
dtype: float64

### 누락된 데이터 추출

In [42]:
pd.isnull(obj4)

Califonia     True
Ohio         False
Oregon       False
Texas        False
dtype: bool

In [43]:
pd.notnull(obj4)

Califonia    False
Ohio          True
Oregon        True
Texas         True
dtype: bool

In [44]:
obj4.isnull()

Califonia     True
Ohio         False
Oregon       False
Texas        False
dtype: bool

### name 속성

In [46]:
obj4.name = 'population'
obj4.index.name = 'state'

In [47]:
obj4

state
Califonia        NaN
Ohio         35000.0
Oregon       16000.0
Texas        71000.0
Name: population, dtype: float64

In [48]:
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan']

In [49]:
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

## Dataframe
- 표 같은 스프레드시트 형식의 자료구조
- 여러개 각 칼럼의 서로 다른 종류의 값(숫자, 문자열, 불리언)담을 수 있음
- 2차원 배열

In [60]:
data = {'state' : ['Ohio','Ohio','Ohio','Nevada','Nevada','Nevada'],
       'year' : [2000, 2001, 2002, 2001, 2002, 2003],
       'pop' : [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = pd.DataFrame(data)

In [61]:
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [62]:
frame.head()

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

### 원하는 순서대로 columns 지정

In [63]:
pd.DataFrame(data, columns=['year', 'state', 'pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

### 인덱스 지정, 접근

In [64]:
frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'],
                     index=['one', 'two', 'three', 'four', 'five', 'six'])

In [66]:
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [68]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [69]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

In [70]:
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

### column 대입
- 리스트나 배열을 칼럼에 대입할 때는 대입하려는 값의 길이가 Dataframe의 크기와 동일해야 한다.
- Series를 대입하면 Dataframe의 색인에 따라 값이 대입되며 존재하지 않는 색인에는 결측치가 대입한다.
- 존재하지 않는 칼럼을 대입하면 새로운 칼럼을 생성한다.
- 복사본이 따로 존재 하지 않아 필요할땐 Series.copy 메서드 이용

In [71]:
frame2['debt'] = 16.5

In [75]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5
six    2003  Nevada  3.2  16.5

In [76]:
frame2['debt'] = np.arange(6.)

In [77]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
six    2003  Nevada  3.2   5.0

In [74]:
val = pd.Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])

In [78]:
frame2['debt'] = val

In [79]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [80]:
frame2['eastern'] = frame2.state == 'Ohio'

In [81]:
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False
six    2003  Nevada  3.2   NaN    False

In [82]:
del frame2['eastern']

In [84]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

### 중첩된 사전 이용
- 바깥에 있는 사전의 키는 Columns, 안에 있는 키는 Rows가 된다

In [85]:
pop = {'Nevada' : {2001 : 2.4, 2002 : 2.9},
      'Ohio' : {2000 : 1.5, 2001 : 1.7, 2002 : 3.6}}

In [86]:
frame3 = pd.DataFrame(pop)

In [88]:
frame3

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

### 데이터 전치

In [89]:
frame3.T

2001  2002  2000
Nevada   2.4   2.9   NaN
Ohio     1.7   3.6   1.5

### 색인 직접 지정

In [90]:
pd.DataFrame(pop, index=[2001,2002,2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

### name 속성

In [91]:
frame3.index.name = 'year'
frame3.columns.name = 'state'

In [92]:
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [93]:
frame3.values

array([[2.4, 1.7],
       [2.9, 3.6],
       [nan, 1.5]])

In [94]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

## 색인 객체
- 표 형식의 데이터에서 각 로우와 칼럼에 대한 이름과 다른 메타데이터(축 이름등)를 저장하는 객체
- Series나 DataFrame 객체를 생성할때 사용되는 배열이나 다른 순차적인 이름은 내부적으로 색인으로 변환

In [96]:
obj = pd.Series(range(3), index=['a', 'b', 'c'])

In [102]:
index = obj.index

In [103]:
index

Index(['a', 'b', 'c'], dtype='object')

- index[1] = 'd'  색인 객체는 변경이 불가능하다

In [104]:
labels = pd.Index(np.arange(3))

In [105]:
labels

Int64Index([0, 1, 2], dtype='int64')

In [106]:
obj2 = pd.Series([1.5, -2.5, 0], index=labels)

In [107]:
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [108]:
obj2.index is labels

True

In [109]:
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [110]:
frame3.columns

Index(['Nevada', 'Ohio'], dtype='object', name='state')

- 파이썬의 집합과는 달리 pandas의 인덱스는 중복되는 값을 허용

In [111]:
dup_labels = pd.Index(['foo', 'foo', 'bar', 'bar'])
dup_labels

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

# 핵심 기능

## 재색인(reindex)

In [112]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])

In [113]:
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [114]:
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'])

In [115]:
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

- method = ffill을 이용해 누락된 값을 직전의 값으로 채워 넣을 수 있다

In [116]:
obj3 = pd.Series(['blue', 'purple', 'yellow'], index=[0, 2, 4])

In [117]:
obj3

0      blue
2    purple
4    yellow
dtype: object

In [118]:
obj3.reindex(range(6), method = 'ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [120]:
frame = pd.DataFrame(np.arange(9).reshape((3, 3)),
                    index=['a', 'c', 'd'],
                    columns = ['Ohio', 'Texas', 'California'])

In [121]:
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [122]:
frame2 = frame.reindex(['a', 'b', 'c', 'd'])

In [123]:
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [124]:
states = ['Texas', 'Utah', 'California']
frame.reindex(columns=states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

## 하나의 로우나 칼럼 삭제하기(drop)

In [134]:
obj = pd.Series(np.arange(5.), index=['a','b','c','d','e'])

In [135]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [136]:
new_obj = obj.drop('c')

In [137]:
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [138]:
obj.drop(['d','c'])

a    0.0
b    1.0
e    4.0
dtype: float64

In [139]:
data = pd.DataFrame(np.arange(16).reshape(4,4),
                   index = ['Ohio','Colorado','Utah','New York'],
                   columns= ['one', 'two', 'three', 'four'])

In [140]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [141]:
data.drop(['Colorado', 'Ohio'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [142]:
data.drop(['two', 'four'], axis=1)

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

In [146]:
obj.drop('c')

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [147]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [148]:
obj.drop('c', inplace=True)

In [149]:
obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

## 색인하기, 선택하기, 거르기
- Series의 색인(obj[...])은 Numpy 배열의 색인과 유사하게 동작하지만 정수가 아니어도 된다는 점이 다르다

In [150]:
obj = pd.Series(np.arange(4.), index=['a', 'b', 'c', 'd'])

In [151]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [152]:
obj['b']

1.0

In [153]:
obj[1]

1.0

In [154]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [155]:
obj[['b', 'a', 'd']]

b    1.0
a    0.0
d    3.0
dtype: float64

In [156]:
obj[[1, 3]]

b    1.0
d    3.0
dtype: float64

In [157]:
obj[obj<2]

a    0.0
b    1.0
dtype: float64

- 라벨 이름으로 슬라이싱하면 시작점과 끝점을 포함한다는 것이 일반 파이썬에서의 슬라이싱과 다른 점이다

In [158]:
obj['b':'c']

b    1.0
c    2.0
dtype: float64

- 슬라이싱 문법으로 선택된 영역에 값을 대입하는 것은 생각하는 대로 동작한다

In [159]:
obj['b':'c'] = 5

In [160]:
obj

a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

- 색인으로 DataFrame에서 하나 이상의 칼럼 값을 가져올 수 있다

In [162]:
data = pd.DataFrame(np.arange(16).reshape((4,4)),
                    index= ['Ohio', 'Colorado', 'Utah', 'New York'],
                    columns= ['one', 'two', 'three', 'four'])

In [163]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [164]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int32

In [165]:
data[['three', 'one']]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

- 슬라이싱으로 로우를 선택하거나 불리언 배열로 로우를 선택할 수 있다

In [166]:
data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [169]:
data[data['three'] > 5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

- DataFrame과 2차원 ndarray 문법적으로 비슷한 요소

In [168]:
data < 5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

- loc, iloc으로 선택하기
 - DataFrame의 로우에 대해 라벨로 색인하는 방법으로 특수한 색인 필드인 loc과 iloc
 - Numpy와 비슷한 방식에 추가적으로 축의 라벨을 사용해 DataFrame의 로우와 칼럼을 선택할 수 있음
 - 축 이름을 선택할땐 loc를, 정수 색인으로 선택할땐 iloc 

In [170]:
data.loc['Colorado', ['two', 'three']]

two      5
three    6
Name: Colorado, dtype: int32

In [171]:
data.iloc[2,[3, 0, 1]]

four    11
one      8
two      9
Name: Utah, dtype: int32

In [172]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int32

In [173]:
data.iloc[[1, 2], [3, 0, 1]]

four  one  two
Colorado     7    4    5
Utah        11    8    9

- 이 두 함수는 슬라이스도 지원할 뿐더러 단일 라벨이나 라벨 리스트도 지원

In [174]:
data.loc[:'Utah', 'two']

Ohio        1
Colorado    5
Utah        9
Name: two, dtype: int32

In [175]:
data.iloc[:, :3][data.three >5]

one  two  three
Colorado    4    5      6
Utah        8    9     10
New York   12   13     14

## 정수 색인
- 파이썬 내장 자료구조에서 색인을 다루는 방법과의 차이점 때문에 실수하게 되는 경우가 있음
- ser = pd.Series(np.arange(3.))
- ser [-1] ==> Error
- 라벨 색인이 0, 1, 2를 포함하는 경우 사용자가 라벨 색인으로 선택하려는 것인지 정수 색인으로 선택하려는 것인지 추측하기 쉽지 않음

In [177]:
ser = pd.Series(np.arange(3.))
ser

0    0.0
1    1.0
2    2.0
dtype: float64

- 정수 기반의 색인을 사용하지 않는 경우 이런 모호함은 사라짐

In [181]:
ser2 = pd.Series(np.arange(3.), index=['a', 'b', 'c'])
ser2[-1]

2.0

- 일관성을 유지하기 위해 정숫값을 담고 있는 축 색인이 있다면 우선적으로 라벨을 먼저 찾아보도록 구현
- 좀 더 세밀하게 사용하고 싶다면 라벨에 대해서는 loc을, 정수 색인에 대해서는 iloc을 사용하자

In [183]:
ser[:1]

0    0.0
dtype: float64

In [184]:
ser.loc[:1]

0    0.0
1    1.0
dtype: float64

In [190]:
ser.iloc[:1]

0    0.0
dtype: float64

## 산술 연산과 데이터 정렬
- pandas에서 가장 중요한 기능 중 하나인 "다른 색인을 가지고 있는 객체 간의 산술 연산"
- 객체를 더할 때 맞지 않는 색인이 있다면 결과에 두 색인이 통합됨
- 색인 라벨에 대한 외부 조인과 유사하게 동작

In [192]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index = ['a', 'c', 'd', 'e'])
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1], index = ['a', 'c', 'e', 'f', 'g'])

In [193]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [198]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

- 서로 겹치는 색인이 없는 경우 데이터는 NA 값이 됨

In [200]:
s1 + s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

- DataFrame의 경우 정렬은 로우와 칼럼 모두에 적용

In [201]:
df1 = pd.DataFrame(np.arange(9.).reshape((3,3)), columns=list('bcd'), index=['Ohio', 'Texas', 'Colorado'])

In [204]:
df2 = pd.DataFrame(np.arange(12.).reshape((4,3)), columns=list('bde'), index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [205]:
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [210]:
df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

- 공통된 칼럼 라벨이나 로우 라벨이 없는 DataFrame을 더하면 결과에 아무것도 나타나지 않을 것이다

In [211]:
df1 + df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [212]:
df1 = pd.DataFrame({'A' : [1, 2]})

In [213]:
df2 = pd.DataFrame({'B' : [3, 4]})

In [214]:
df1

A
0  1
1  2

In [215]:
df2

B
0  3
1  4

In [216]:
df1 - df2

A   B
0 NaN NaN
1 NaN NaN

- 산술 연산 메서드에 채워 넣을 값 지정하기
 - 서로 다른 색인을 가지는 객체간의 산술 연산에서 존재하지 않는 축의 값을 특수한 값(0과 같은)으로 지정하고 싶을때

In [220]:
df1 = pd.DataFrame(np.arange(12.).reshape((3,4)), columns=list('abcd'))

In [221]:
df2 = pd.DataFrame(np.arange(20.).reshape((4,5)), columns=list('abcde'))

In [222]:
df2.loc[1, 'b'] = np.nan

In [223]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [224]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [227]:
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

- 겹치지 않는 부분도 나타나게 함
- fill_value = 0 기존 겹치지 않는 값 그대로 사용 1, 2, 3 ... 기존 값에 더하여 출력

In [231]:
df1.add(df2, fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

- 재색인 할때도 fill_value 지정가능

In [232]:
df1.reindex(columns=df2.columns, fill_value=0)

a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

- DataFrame과 Series 간의 연산

In [234]:
arr= np.arange(12.).reshape((3, 4))

In [235]:
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [240]:
arr[0]

array([0., 1., 2., 3.])

- arr에서 arr[0]을 빼면 계산은 각 로우에 대해 한 번씩만 수행됨, 이를 "브로드 캐스팅"이라고 함

In [241]:
arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [242]:
frame = pd.DataFrame(np.arange(12.).reshape((4,3)),
                    columns=list('bcd'),
                    index= ['Utah', 'Ohio', 'Texas', 'Oregon'])

In [243]:
series = frame.iloc[0]

In [244]:
frame

b     c     d
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [245]:
series

b    0.0
c    1.0
d    2.0
Name: Utah, dtype: float64

- 기본적으로 DataFrame과 Series 간의 산술 연산은 Series의 색인을 DataFrame의 칼럼에 맞추고 아래 로우로 전파

In [247]:
frame - series

b    c    d
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

- 각 로우에 대해 연산을 수행하고 싶다면 산술 연산 메사드 사용

In [262]:
series3 = frame['d']

In [263]:
series3

Utah       2.0
Ohio       5.0
Texas      8.0
Oregon    11.0
Name: d, dtype: float64

In [261]:
frame

b     c     d
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [265]:
frame.sub(series3, axis=0)

b    c    d
Utah   -2.0 -1.0  0.0
Ohio   -2.0 -1.0  0.0
Texas  -2.0 -1.0  0.0
Oregon -2.0 -1.0  0.0

## 함수 적용과 매핑
- pandas 객체에도 Numpy 유니버설 함수(배열의 각 원소에 적용되는 메서드)를 적용할 수 있다

In [266]:
frame = pd.DataFrame(np.random.randn(4,3), columns=list('bde'),
                    index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [267]:
frame

b         d         e
Utah   -1.293950 -0.655589  0.330339
Ohio   -0.048623  0.888039  0.265625
Texas  -0.597077  0.207788 -1.183860
Oregon  2.146609  0.110249  0.836033

In [268]:
np.abs(frame)

b         d         e
Utah    1.293950  0.655589  0.330339
Ohio    0.048623  0.888039  0.265625
Texas   0.597077  0.207788  1.183860
Oregon  2.146609  0.110249  0.836033

- 자주 사용되는 연산으로 각 칼럼이나 로우의 1차원 배열에 함수를 적용한다
- DataFrame의 apply 메서드 이용
 - 함수 f 는 Series의 최댓값과 최솟값의 차이를 계산하는 함수
 - frame의 각 칼럼에 대해 한 번만 수행되며 결괏값은 계산을 적용한 칼럼을 색인으로 하는 Series 반환

In [270]:
f = lambda x: x.max() - x.min()

In [271]:
frame.apply(f)

b    3.440559
d    1.543628
e    2.019894
dtype: float64

In [273]:
frame.apply(f, axis=1)

Utah      1.624289
Ohio      0.936663
Texas     1.391649
Oregon    2.036360
dtype: float64

## 정렬과(sort_index) 순위(rank)

In [275]:
obj = pd.Series(range(4), index=['d', 'a', 'b', 'c'])

In [277]:
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [278]:
frame = pd.DataFrame(np.arange(8).reshape((2, 4)),
                    index=['three', 'one'],
                    columns=['d', 'a', 'b', 'c'])

In [279]:
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [280]:
frame.sort_index(axis=1)

a  b  c  d
three  1  2  3  0
one    5  6  7  4

- 오름차순 내림차순으로 정렬할 수도 있다

In [281]:
frame.sort_index(axis=1, ascending=False)

d  c  b  a
three  0  3  2  1
one    4  7  6  5

- 값에 따라 정렬(sort_values)

In [282]:
obj = pd.Series([4, 7, -3, 2])

In [283]:
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

- 정렬할 때 비어 있는 값은 기본적으로 Series 객체에서 가장 마지막에 위치

In [284]:
obj = pd.Series([4, np.nan, 7, np.nan, -3, 2])

In [285]:
obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [286]:
frame = pd.DataFrame({'b': [4, 7, -3, 2], 'a':[0,1,0,1]})

In [291]:
frame

b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [294]:
frame = frame.sort_index(axis=1)

In [295]:
frame.sort_values(by='b')

a  b
2  0 -3
3  1  2
0  0  4
1  1  7

In [296]:
frame.sort_values(by=['a','b'])

a  b
2  0 -3
0  0  4
3  1  2
1  1  7

- 순위(Rank) 동점인 항목에 대해서 평균 순위를 매김

In [297]:
obj = pd.Series([7, -5, 7, 4, 2, 0, 4])

In [298]:
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [299]:
obj.rank(method='first')

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [300]:
# 동률인 경우 그룹 내에서 높은 순위를 적용한다.
obj.rank(ascending = False, method='max')

0    2.0
1    7.0
2    2.0
3    4.0
4    5.0
5    6.0
6    4.0
dtype: float64

In [301]:
frame = pd.DataFrame({'b' : [4.3, 7, -3, 2], 'a': [0, 1, 0, 1], 'c' : [-2, 5, 8, -2.5]})

In [305]:
frame = frame.sort_index(axis=1)

In [306]:
frame

a    b    c
0  0  4.3 -2.0
1  1  7.0  5.0
2  0 -3.0  8.0
3  1  2.0 -2.5

In [309]:
frame.rank(axis=1)

a    b    c
0  2.0  3.0  1.0
1  1.0  3.0  2.0
2  2.0  1.0  3.0
3  2.0  3.0  1.0

## 중복 색인
- 중복된 색인 값을 가짐

In [311]:
obj = Series(range(5), index = ['a', 'a', 'b', 'b', 'c'])

In [312]:
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [318]:
obj.index.is_unique

False

- 중복되는 색인값이 있을 때는 하나의 Series(=벡터값)로 반환 

In [320]:
obj['a']

a    0
a    1
dtype: int64

- 중복되는 색인 값이 없을땐 스칼라값(1개)을 반환

In [316]:
obj['c']

4

# 기술 통계 계산과 요약
- 누락된 데이터 제외
- 단일 값(합이나 평균 같은)을 구하는 축소 혹은 요약통계 범주에 속함

In [324]:
df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5], [np.nan, np.nan], [0.75, -1.3]],
                 index = ['a', 'b', 'c', 'd'], columns=['one', 'two'])

In [325]:
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [322]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [323]:
df.sum(axis=1)

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [326]:
df.mean(axis='columns', skipna=False)

a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

In [327]:
df.idxmax()

one    b
two    d
dtype: object

In [328]:
df.describe()

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

- 수치 데이터가 아닐 경우

In [329]:
obj = pd.Series(['a', 'a', 'b', 'c'] * 4)

In [330]:
obj.describe()

count     16
unique     3
top        a
freq       8
dtype: object

## 유일값(Unique), 값 세기(Value_counts), 멤버십

In [331]:
obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c'])

In [332]:
uniques = obj.unique()

In [333]:
uniques

array(['c', 'a', 'd', 'b'], dtype=object)

In [335]:
obj.value_counts()

a    3
c    3
b    2
d    1
dtype: int64

In [336]:
pd.value_counts(obj.values, sort=False)

a    3
d    1
b    2
c    3
dtype: int64